export enum ACTIONS {
  LOAD_COUNTRIES = "LOAD_COUNTRIES",
  LOAD_RESTRICTIONS = "LOAD_RESTRICTIONS",
  CHECK_FILTERS = "CHECK_FILTERS",
  SEARCH = "SEARCH",
  RESET_SANCTIONS_DB_WITH_FILE = "RESET_SANCTIONS_DB_WITH_FILE",
  AUTH = "AUTH",
  REGISTER = "REGISTER",
  VERIFY = "VERIFY",
}

export const UNAUTHORIZED_ACTIONS = [
  ACTIONS.AUTH,
  ACTIONS.REGISTER,
  ACTIONS.CHECK_FILTERS,
  ACTIONS.LOAD_COUNTRIES,
  ACTIONS.LOAD_RESTRICTIONS,
  ACTIONS.SEARCH,
];
